version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-50-19-127-115.compute-1.amazonaws.com
            database: d8fthcps66a0sr
            schema: public
            user: eiirumyzsugfbs
            password: dc2bcce365c9917ff5c9844553435a40e21ac17f380086d21c3e1e4350e37532
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true